### ISSUE TITLE
RFC: Move project and docker images to `dockbuild` organization ? 

### ISSUE THREAD

**Issue by jcfr** [dockcross/centos-build#12]
Instead of maintainer the image on `thewtex`, what do you think of creating a GitHub organization named `dockbuild`  (similar to the existing `dockcross` one) ?

Cc: @thewtex

**Comment by jcfr** [comment]
Or we could transfer and rename the project to https://github.com/dockcross/centos-build ?

**Comment by thewtex** [comment]
> Or we could transfer and rename the project to https://github.com/dockcross/centos-build ?

Seems reasonable to combine similar projects and avoid creation / management of another organization. I'll act on this...

**Comment by thewtex** [comment]
All set!

**Comment by jcfr** [comment]
Thanks @thewtex

**Comment by jcfr** [comment]
Could you enable CircleCi build ? 

![centos-build-circleci](https://user-images.githubusercontent.com/219043/36651893-3f88f4fc-1a79-11e8-918e-104dcff62f26.png)

**Comment by thewtex** [comment]
@jcfr enabled. Also added you and @fedorov to repo admins.
